dist: trusty
sudo: false
os:
  - linux
install:
  - git clone --depth 1 --recurse-submodules https://github.com/keyboardio/Kaleidoscope-Bundle-Keyboardio hardware/keyboardio
script:
  - make travis-test BOARD_HARDWARE_PATH=$(pwd)/hardware
notifications:
  email:
    on_success: change
    on_failure: change
cache:
  ccache: true
